### ISSUE TITLE
A bug: too many values to unpack

### ISSUE THREAD

**Issue by pengxiao-song** [ningkp/LfOSA#2]
Position: https://github.com/ningkp/LfOSA/blob/master/AL_center_temperature.py#L241
Bug info shows as followed
```
Traceback (most recent call last):
  File "AL_center_temperature.py", line 395, in <module>
    main()
  File "AL_center_temperature.py", line 151, in main
    trainloader_A, invalidList, use_gpu, dataset.num_classes, epoch)
  File "AL_center_temperature.py", line 243, in train_A
    for batch_idx, (index, (data, labels)) in enumerate(trainloader):
ValueError: too many values to unpack (expected 2)
```

So, please, why doesn't it work well ??
Thanks!!

**Comment by pengxiao-song** [comment]
> 

I guess the interface of cifar10 in torchvision is changed by u, but it doesn't seem like a good operation. So wait for your teaching!! Thanks!

**Comment by ningkp** [comment]
Yes, for a better experiment, we modified the "dataloader.py" as follows,
![image](https://user-images.githubusercontent.com/27044503/193314351-787abb47-756d-48f4-88b5-11199562643d.png)

**Comment by pengxiao-song** [comment]
> 

Thank u! But I think a better way is customize a dataset so that we could replace `__getitem__` method.
